-- ddl script
-- automatically executed on postgres first startup 

-- dim_policy: SCD2 - policy contract state (status, premium_amount)
-- dim_driver: SCD1 - policyholder identity and contact details
-- dim_vehicle: insured vehicle attributes
-- dim_coverage: coverage product tiers
-- dim_date: standard calendar dimension, populated by the warehouse loader
-- fact_policy: fact - grain = policy_id

-- dq observability tables:
-- dq_run_metrics: per-run record written by dq_metrics.py
-- etl_runs: run-level audit status for success/failure visibility
--
-- etl state tables:
-- etl_ingestion_batches: ingestion marker by batch; marks batches that have successfully produced valid/invalid outputs
-- etl_scd_batches: SCD marker by batch and dimension, including warehouse_loaded_at


-- dim_policy (SCD2)
-- tracks changes to the two policy contract attributes that require historical versioning: status and premium_amount
CREATE TABLE IF NOT EXISTS dim_policy (
    policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- source-system policy id
    source_policy_id VARCHAR(50) NOT NULL,
    source_driver_id VARCHAR(20), 
    source_vehicle_id VARCHAR(50),
    source_coverage_id VARCHAR(50),
    premium_amount DECIMAL(10,2),
    status VARCHAR(20),
    source_batch_date DATE,
    processed_run_id VARCHAR(100),
    ingestion_dt TIMESTAMP,
    -- SCD2 validity (start_date = first-seen source_batch_date; end_date sentinel 2099-12-31 = open version)
    start_date DATE NOT NULL DEFAULT DATE '1900-01-01',
    end_date DATE NOT NULL DEFAULT DATE '2099-12-31',
    is_current BOOLEAN NOT NULL DEFAULT TRUE, -- TRUE for the single open version of each policy
    last_updated_run_id VARCHAR(100), -- run_id that most recently refreshed or closed this version row
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_dim_policy_status
        CHECK (status IS NULL OR status IN ('active','suspended','cancelled')),
    CONSTRAINT uix_dim_policy_nk UNIQUE (source_policy_id, start_date)
);

CREATE OR REPLACE VIEW v_policy_current AS
SELECT * FROM dim_policy WHERE is_current = TRUE;

-- dim_driver (SCD1)
-- SCD1: overwrite city, country, phone_number, email in place
CREATE TABLE IF NOT EXISTS dim_driver (
    driver_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- source-system license number (license_number in source input)
    source_driver_id VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    surname VARCHAR(100),
    birth_year INTEGER, -- age computed at query time
    city VARCHAR(100),
    country VARCHAR(50),
    phone_number VARCHAR(20),
    email VARCHAR(150),
    source_batch_date DATE,
    processed_run_id VARCHAR(100),
    ingestion_dt TIMESTAMP,
    last_updated_run_id VARCHAR(100), -- run_id that most recently refreshed this SCD1 row
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_dim_driver_country
        CHECK (country IS NULL OR country IN ('GB','FR','DE','ES','IT','NL')),
    CONSTRAINT uix_dim_driver UNIQUE (source_driver_id)
);

-- dim_vehicle
CREATE TABLE IF NOT EXISTS dim_vehicle (
    vehicle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- vehicle plate number (plate_number in source input)
    source_vehicle_id VARCHAR(50) NOT NULL,
    vehicle_make VARCHAR(50),
    vehicle_model VARCHAR(50),
    vehicle_type VARCHAR(50),
    vehicle_year INTEGER,
    source_batch_date DATE,
    processed_run_id VARCHAR(100),
    ingestion_dt TIMESTAMP,
    last_updated_run_id VARCHAR(100), -- run_id that inserted this row (no further refresh occurs)
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_dim_vehicle_type
        CHECK (vehicle_type IS NULL OR vehicle_type IN ('sedan','suv','truck')),
    CONSTRAINT uix_dim_vehicle UNIQUE (source_vehicle_id)
);


-- dim_coverage
-- 3 product tiers: basic, standard, premium.
-- populated by the scd_and_warehouse.py
CREATE TABLE IF NOT EXISTS dim_coverage (
    coverage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- string tier code (basic/standard/premium)
    source_coverage_id VARCHAR(50) NOT NULL,
    coverage_description VARCHAR(200),
    coverage_limit_amount NUMERIC(14,2), -- maximum claim payout for this tier
    deductible_amount NUMERIC(14,2), -- policy-holder deductible for this tier
    is_active BOOLEAN NOT NULL DEFAULT TRUE, -- always TRUE
    source_batch_date DATE,
    processed_run_id VARCHAR(100),
    ingestion_dt TIMESTAMP,
    last_updated_run_id VARCHAR(100), -- run_id that inserted this row (no further refresh occurs)
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_dim_coverage_id
        CHECK (source_coverage_id IN ('basic','standard','premium')),
    CONSTRAINT uix_dim_coverage UNIQUE (source_coverage_id)
);


-- dim_date (standard calendar dimension)
-- populated by ensure_dim_date_rows (warehouse_loader.py) as part of the fact load step, covering the year span of any pending fact batch dates
CREATE TABLE IF NOT EXISTS dim_date (
    date_id INTEGER PRIMARY KEY, -- Surrogate key YYYYMMDD
    date DATE NOT NULL UNIQUE,
    year INTEGER NOT NULL,
    quarter INTEGER NOT NULL,
    month INTEGER NOT NULL,
    month_name VARCHAR(20) NOT NULL,
    day INTEGER NOT NULL,
    day_of_week INTEGER NOT NULL,
    day_name VARCHAR(20) NOT NULL,
    week_of_year INTEGER NOT NULL,
    is_weekend BOOLEAN NOT NULL,
    is_month_start BOOLEAN NOT NULL,
    is_month_end BOOLEAN NOT NULL,
    is_quarter_start BOOLEAN NOT NULL,
    is_quarter_end BOOLEAN NOT NULL
);


-- fact_policy
-- grain: one row per dim_policy version (policy_id).
CREATE TABLE IF NOT EXISTS fact_policy (
    fact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id BIGINT NOT NULL REFERENCES dim_policy(policy_id),
    driver_id BIGINT NOT NULL REFERENCES dim_driver(driver_id),
    vehicle_id BIGINT NOT NULL REFERENCES dim_vehicle(vehicle_id),
    coverage_id BIGINT NOT NULL REFERENCES dim_coverage(coverage_id),
    date_id INTEGER NOT NULL REFERENCES dim_date(date_id),
    annual_premium_amount NUMERIC(12,2), -- premium for this specific policy version (from dim_policy.premium_amount)
    loaded_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT uix_fact_policy UNIQUE (policy_id)
);

-- dq_run_metrics
-- DQ metrics are stored as per-run record, used by grafana 
-- written by dq_metrics.py
-- queried by grafana dq dashboard panels 
CREATE TABLE IF NOT EXISTS dq_run_metrics (
    run_id VARCHAR(100) PRIMARY KEY, -- matches the Airflow run_id used throughout the pipeline run
    measured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    input_records INTEGER,
    valid_records INTEGER,
    invalid_records INTEGER,
    total_records INTEGER,
    valid_rate NUMERIC(6,2),
    invalid_rate NUMERIC(6,2),
    reconciliation_difference INTEGER,
    batch_count INTEGER,
    per_batch_valid JSONB,
    per_batch_invalid JSONB,
    valid_duplicate_rate NUMERIC(6,2),
    invalid_duplicate_rate NUMERIC(6,2),
    invalid_error_breakdown JSONB,
    dim_policy_total_rows INTEGER,
    dim_policy_current_rows INTEGER,
    dim_policy_historical_rows INTEGER,
    dim_driver_total_rows INTEGER,
    dim_vehicle_total_rows INTEGER,
    dim_coverage_total_rows INTEGER,
    fact_rows INTEGER
);

CREATE TABLE IF NOT EXISTS etl_runs (
    run_id VARCHAR(100) PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'running'
        CHECK (status IN ('running','success','failed')),
    error_text TEXT
);


-- etl state: incremental + idempotent batch markers
CREATE TABLE IF NOT EXISTS etl_ingestion_batches (
    batch_date DATE PRIMARY KEY,
    run_id VARCHAR(100) NOT NULL,
    first_processed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    input_record_count INTEGER
);

CREATE TABLE IF NOT EXISTS etl_scd_batches (
    batch_date DATE NOT NULL,
    dimension_name VARCHAR(50) NOT NULL,
    contract_version VARCHAR(20),
    run_id VARCHAR(100) NOT NULL,
    first_processed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    warehouse_loaded_at TIMESTAMPTZ,
    PRIMARY KEY (batch_date, dimension_name)
);


-- mart views

-- current active policies grouped by coverage tier with premium aggregates
CREATE OR REPLACE VIEW mart_active_policies_by_coverage AS
SELECT
    dc.source_coverage_id AS coverage_tier,
    COUNT(DISTINCT p.source_policy_id) AS active_policy_count,
    AVG(f.annual_premium_amount)::NUMERIC(10, 2) AS avg_premium,
    SUM(f.annual_premium_amount)::NUMERIC(14, 2) AS total_premium
FROM fact_policy f
JOIN dim_policy p ON f.policy_id = p.policy_id
JOIN dim_coverage dc ON f.coverage_id = dc.coverage_id
WHERE p.is_current = TRUE
  AND p.status = 'active'
GROUP BY dc.source_coverage_id;

-- premium revenue broken down by policy batch month (dim_date via fact_policy.date_id, derived from dim_policy.source_batch_date) and driver country
CREATE OR REPLACE VIEW mart_premium_by_month_country AS
SELECT
    dd.year,
    dd.month,
    dd.month_name,
    dr.country,
    COUNT(DISTINCT p.source_policy_id) AS policy_version_count,
    SUM(f.annual_premium_amount)::NUMERIC(14, 2) AS total_premium
FROM fact_policy f
JOIN dim_policy p ON f.policy_id = p.policy_id
JOIN dim_driver dr ON f.driver_id = dr.driver_id
JOIN dim_date dd ON f.date_id = dd.date_id
GROUP BY dd.year, dd.month, dd.month_name, dr.country
ORDER BY dd.year, dd.month, dr.country;

-- full SCD2 history for each policy
CREATE OR REPLACE VIEW mart_policy_version_history AS
SELECT
    p.source_policy_id,
    p.start_date,
    p.end_date,
    p.is_current,
    p.status,
    p.premium_amount,
    dr.source_driver_id,
    dc.source_coverage_id
FROM dim_policy p
LEFT JOIN dim_driver dr
    ON p.source_driver_id = dr.source_driver_id
LEFT JOIN dim_coverage dc
    ON p.source_coverage_id = dc.source_coverage_id
ORDER BY p.source_policy_id, p.start_date;


-- verification
DO $$
BEGIN
    RAISE NOTICE 'Star schema initialization complete';
    RAISE NOTICE 'Tables created: dim_policy, dim_driver, dim_vehicle, dim_coverage, dim_date, fact_policy';
    RAISE NOTICE 'DQ tables created: dq_run_metrics';
    RAISE NOTICE 'ETL state tables created: etl_runs, etl_ingestion_batches, etl_scd_batches';
END $$;
